// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinderZaBendeBackend.Data;

#nullable disable

namespace TinderZaBendeBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinderZaBendeBackend.Models.Entities.Uporabnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("geslo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("instrument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("kraj_id")
                        .HasColumnType("integer");

                    b.Property<string>("telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("zanr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Uporabniki");
                });
#pragma warning restore 612, 618
        }
    }
}
